# Jack Robbins
## 10/28/2022
## Numpy Exercises 
Textbook exercises: 7.1, 7.3, 7.4, 7.5

In [1]:
#Need Numpy to do exercises
import numpy as np

7.1 (Filling arrays) Fill a 2-by-3 array with ones, a 3-by-3 array with zeros and a 2-by-5 array with 7s.

In [9]:
arr_2by3 = np.array([[1,1,1,], [1,1,1]])

arr_3by3 = np.array([[0,0,0], [0,0,0], [0,0,0]])

arr_2by5 = np.array([[7,7,7,7,7],[7,7,7,7,7]])


7.3 (Element-Wise array Multiplication) Create a 3-by-3 array containing the even integers from 2 through 18. Create a second 3-by-3 array containing the integers from 9 down to 1, then multiply the first array by the second.

In [12]:
even_int_arr = np.array([[2, 4, 6], [8,10,12], [14,16,18]])
less_9_arr = np.array([[9,8,7], [6,5,4], [3,2,1]])
multiplied = np.multiply(even_int_arr, less_9_arr)
print(multiplied)

[[18 32 42]
 [48 50 48]
 [42 32 18]]


7.4 (array from List of Lists) Create a 2-by-5 array from an argument which is a list of the two five-element lists [2, 3, 5, 7, 11] and [13, 17, 19, 23, 29].

In [13]:
def array_from_lists(list_of_lists):
    return np.array(list_of_lists)



array_elements = [[2,3,5,7,11], [13,17,19,23,29]]
print(array_from_lists(array_elements))

[[ 2  3  5  7 11]
 [13 17 19 23 29]]


7.9 (Indexing and Slicing arrays) Create an array containing the values 1–15, reshape it into a 3-by-5 array, then use indexing and slicing techniques to perform each of the following operations:

1. Select row 2.
2. Select column 5. (? There is no column 5. Selecting row 4 instead)
3. Select rows 0 and 1.
4. Select columns 2–4.
5. Select the element that is in row 1 and column 4.
6. Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.

In [48]:
my_arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]).reshape((3,5))
print(my_arr)

print(f"Selecting row 2: {my_arr[2]}")
print(f"Selecting column 4: {my_arr[:,4]}")
print(f"Selecting rows 0 and 1:\n{my_arr[1:]}")
print(f"Selecting columns 2-4:\n{my_arr[:,[2,4]]}")
print(f"Selecting the element that is in row 1 and column 4:\n{my_arr[1,4]}")
print(f"Selecting all elements from rows 1 and 2 in columns 0,2,and 4:\n{my_arr[1:3:,0:5:2]}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Selecting row 2: [11 12 13 14 15]
Selecting column 4: [ 5 10 15]
Selecting rows 0 and 1:
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
Selecting columns 2-4:
[[ 3  5]
 [ 8 10]
 [13 15]]
Selecting the element that is in row 1 and column 4:
10
Selecting all elements from rows 1 and 2 in columns 0,2,and 4:
[[ 6  8 10]
 [11 13 15]]
